#!/bin/bash
total 12
-rw-r--r-- 1 holberton holberton  82 ene 29 09:38 0-current_working_directory
-rw-r--r-- 1 holberton holberton 155 ene 29 09:39 1-listit
-rw-r--r-- 1 holberton holberton  15 ene 29 09:42 2-bring_me_home
-rw-r--r-- 1 holberton holberton   0 ene 29 09:46 3-listfiles
